name: CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: pwsh

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python: ["3.10"]
        experimental: [false]
    continue-on-error: ${{ matrix.experimental }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
      with:
        persist-credentials: false
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: 'x64'
    - name: Restore
      run: |
        python -m pip install -r requirements.txt
    - name: Test
      env:
        PYTHONUTF8: 1
      run: |
        cb
  mirror:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    continue-on-error: false
    steps:
    - name: mirror
      run: |
        git clone "https://github.com/StardustDL/coxbuild-ext-gallery.git"
        cd "coxbuild-ext-gallery"
        git remote add gitee "https://stardustdl:${{ secrets.GITEE_KEY }}@gitee.com/stardustdl/coxbuild-ext-gallery.git"
        git remote set-head origin -d
        git push gitee --prune +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
        cd ..